
influxdb:
  image: influxdb:latest
  container_name: influxdb
  ports:
    - "8086:8086"
    - "2003:2003"
  env_file:
    - 'env.influxdb'
  volumes:
    - /tmp/tasks/influxdb.conf:/etc/influxdb/influxdb.conf 
    - /srv/docker/influxdb/data:/tmp/influxdb/data
    
grafana:
  image: grafana/grafana:latest
  container_name: grafana
  ports:
    - "3030:3000"
  env_file:
    - 'env.grafana'
  links:
    - influxdb
  volumes:
    - /tmp/tasks/grafana.ini:/etc/grafana/grafana.ini
    - /srv/docker/grafana/data:/tmp/grafana 