
nginx:
  image: sameersbn/nginx:1.15.8
  ports:
    - "80:80"
  volumes:
    #- ./influxdb.conf:/etc/influxdb/influxdb.conf:ro
    - /srv/docker/nginx/sites-enabled:/etc/nginx/sites-enabled
  restart: always
  
influxdb:
  image: influxdb:latest
  container_name: influxdb
  ports:
    - "8086:8086"
    - "2003:2003"
  env_file:
    - 'env.influxdb'
  volumes:
   # - ./influxdb.conf:/etc/influxdb/influxdb.conf:ro 
    - /srv/docker/influxdb/data:/tmp/influxdb
    
grafana:
  image: grafana/grafana:latest
  container_name: grafana
  ports:
    - "3030:3000"
  env_file:
    - 'env.grafana'
  links:
    - influxdb
  volumes:
    - /srv/docker/grafana/data:/tmp/grafana
