FROM openjdk:8-jre-slim

ENV JAVA_OPTS="-Xmx1g -XX:+HeapDumpOnOutOfMemoryError -XX:HeapDumpPath=/tmp -Djava.security.egd=file:/dev/./urandom -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=5005"
ENV JOLOKIA_AGENT="-javaagent:/opt/java/jolokia-jvm-1.6.0-agent.jar=port=7777,host=localhost"
ENV JAVA_APP=/app.jar


RUN apt-get update \
  && apt-get install -y wget \
  && rm -rf /var/lib/apt/lists/*

RUN apt-get update && \
    apt-get install -y fonts-noto net-tools && \
    rm -rf /var/lib/apt/lists/*

 # Installing Telegraf
RUN cd /tmp && wget https://dl.influxdata.com/telegraf/releases/telegraf_1.8.3-1_amd64.deb && \
    dpkg -i telegraf_1.8.3-1_amd64.deb
COPY ./docker/telegraf.conf /etc/telegraf/telegraf.conf

RUN sh -c "echo '#!/bin/sh \n\
service telegraf restart \n\
#exec java $JOLOKIA_AGENT $JAVA_OPTS -jar $JAVA_APP' > /start.sh && chmod +x /start.sh"

EXPOSE 8080

ENTRYPOINT /start.sh